In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
from sklearn import linear_model

In [3]:
df=pd.read_csv("heart_disease.csv")
df.head()

Name  Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS  \
0       Ram   40      M           ATA        140          289          0   
1    Sunita   49      F           NAP        160          180          0   
2  Mohammed   37      M           ATA        130          283          0   
3     Anita   48      F           ASY        138          214          0   
4       Sri   54      M           NAP        150          195          0   

  RestingECG  MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0     Normal    172              N      0.0       Up             0  
1     Normal    156              N      1.0     Flat             1  
2         ST     98              N      0.0       Up             0  
3     Normal    108              Y      1.5     Flat             1  
4     Normal    122              N      0.0       Up             0

In [5]:
df.columns

Index(['Name', 'Age', 'Gender', 'ChestPainType', 'RestingBP', 'Cholesterol',
       'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak',
       'ST_Slope', 'HeartDisease'],
      dtype='object')

In [11]:
label_encoder= LabelEncoder()
df['ChestPainType']=label_encoder.fit_transform(df['ChestPainType'])
df['HeartDisease']=label_encoder.fit_transform(df['HeartDisease'])
x=df.drop(['Name','Age','Gender','HeartDisease','RestingECG','ExerciseAngina','ST_Slope'],axis=1)
y=df['HeartDisease']

In [12]:
x.head()

ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0              1        140          289          0    172      0.0
1              2        160          180          0    156      1.0
2              1        130          283          0     98      0.0
3              0        138          214          0    108      1.5
4              2        150          195          0    122      0.0

In [15]:
scaler=StandardScaler()

In [16]:
x=scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [22]:
#Random forest classifier
classifier1=RandomForestClassifier(n_estimators=100,random_state=42)

In [23]:
classifier1.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [24]:
preds=classifier1.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [21]:
cm=confusion_matrix(y_test,preds)
report=classification_report(y_test,preds)
print("Accuracy:",accuracy_score(y_test,preds))
print("Confusion matrix:",cm)
print("Report:",report)

Accuracy: 0.8316831683168316
Confusion matrix: [[42  7]
 [10 42]]
Report:               precision    recall  f1-score   support

           0       0.81      0.86      0.83        49
           1       0.86      0.81      0.83        52

    accuracy                           0.83       101
   macro avg       0.83      0.83      0.83       101
weighted avg       0.83      0.83      0.83       101



In [25]:
#Support Vector Machine
from sklearn.svm import SVC
classifier2=SVC(kernel='rbf',random_state=0)
classifier2.fit(x_train,y_train)

SVC(random_state=0)

In [26]:
y_pred=classifier2.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [28]:
cm=confusion_matrix(y_test,preds)
print("Accuracy:",accuracy_score(y_test,preds))
print("Confusion matrix:",cm)

Accuracy: 0.8316831683168316
Confusion matrix: [[42  7]
 [10 42]]


In [32]:
#K Neighbors Classifier knn
from sklearn.neighbors import KNeighborsClassifier
classifer3=KNeighborsClassifier(n_neighbors=7)
classifer3.fit(x_train,y_train)
print("Predictions:\n",classifer3.predict(x_test))
print("Accuracy score:\n",classifer3.score(x_test,y_test))

Predictions:
 [0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 0
 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1]
Accuracy score:
 0.8217821782178217


In [36]:
#Naive bayes
from sklearn.naive_bayes import GaussianNB
classifer4=GaussianNB()
classifer4.fit(x_train,y_train)
preds=classifer4.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,preds)
print("Confusion matrix:",cm)

Confusion matrix: [[48  1]
 [17 35]]


# Preprocessing Methods

In [38]:
df=pd.read_csv("heart_disease.csv")
df.head()
df.columns
label_encoder= LabelEncoder()
df['ChestPainType']=label_encoder.fit_transform(df['ChestPainType'])
df['HeartDisease']=label_encoder.fit_transform(df['HeartDisease'])
x=df.drop(['Name','Age','Gender','HeartDisease','RestingECG','ExerciseAngina','ST_Slope'],axis=1)
y=df['HeartDisease']

In [39]:
print(x)
print(y)

     ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0                1        140          289          0    172      0.0
1                2        160          180          0    156      1.0
2                1        130          283          0     98      0.0
3                0        138          214          0    108      1.5
4                2        150          195          0    122      0.0
..             ...        ...          ...        ...    ...      ...
396              3        140            0          1    143      0.0
397              0        170            0          1    105      0.0
398              0        165            0          1    122      1.0
399              2        200            0          1     70      0.0
400              0        160            0          1    110      0.0

[401 rows x 6 columns]
0      0
1      1
2      0
3      1
4      0
      ..
396    1
397    1
398    1
399    1
400    1
Name: HeartDisease, Length: 401, dtyp

In [43]:
#standard scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
print("Original Data:",x[:10])
print("Scaled data:",x_scaled[:10])

Original Data:    ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0              1        140          289          0    172      0.0
1              2        160          180          0    156      1.0
2              1        130          283          0     98      0.0
3              0        138          214          0    108      1.5
4              2        150          195          0    122      0.0
5              2        120          339          0    170      0.0
6              1        130          237          0    170      0.0
7              1        110          208          0    142      0.0
8              0        140          207          0    130      1.5
9              1        120          284          0    120      0.0
Scaled data: [[ 0.3167346   0.42933254  0.87585565 -0.49922058  1.48630155 -0.65515716]
 [ 1.460974    1.47654878 -0.00483575 -0.49922058  0.84638001  0.41236832]
 [ 0.3167346  -0.09427558  0.82737722 -0.49922058 -1.47333556 -0.65515716]

In [45]:
#minmaxscaler
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x_scaled=scaler.fit_transform(x)
print("Original Data:",x[:10])
print("Scaled data:",x_scaled[:10])

Original Data:    ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0              1        140          289          0    172      0.0
1              2        160          180          0    156      1.0
2              1        130          283          0     98      0.0
3              0        138          214          0    108      1.5
4              2        150          195          0    122      0.0
5              2        120          339          0    170      0.0
6              1        130          237          0    170      0.0
7              1        110          208          0    142      0.0
8              0        140          207          0    130      1.5
9              1        120          284          0    120      0.0
Scaled data: [[0.33333333 0.5        0.47927032 0.         0.86153846 0.34210526]
 [0.66666667 0.66666667 0.29850746 0.         0.73846154 0.47368421]
 [0.33333333 0.41666667 0.46932007 0.         0.29230769 0.34210526]
 [0.         0.48

In [46]:
#Normalizer
from sklearn.preprocessing import Normalizer
scaler=Normalizer(norm='l2')
x_normalized = scaler.fit_transform(x)
print("Original Data:",x[:10])
print("Scaled data:",x_normalized[:10])

Original Data:    ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0              1        140          289          0    172      0.0
1              2        160          180          0    156      1.0
2              1        130          283          0     98      0.0
3              0        138          214          0    108      1.5
4              2        150          195          0    122      0.0
5              2        120          339          0    170      0.0
6              1        130          237          0    170      0.0
7              1        110          208          0    142      0.0
8              0        140          207          0    130      1.5
9              1        120          284          0    120      0.0
Scaled data: [[0.00274508 0.38431095 0.7933276  0.         0.47215345 0.        ]
 [0.00696983 0.55758607 0.62728433 0.         0.54364642 0.00348491]
 [0.00306291 0.39817774 0.8668023  0.         0.30016475 0.        ]
 [0.         0.49

In [8]:
#One hot encoder
from sklearn.preprocessing import OneHotEncoder
scaler=OneHotEncoder()
import pandas as pd
df=pd.read_csv("heart_disease.csv")
x=df.drop(['Name','Age','Gender','HeartDisease','RestingECG','ExerciseAngina','ST_Slope'],axis=1)
y=df['HeartDisease']
x_encoded=scaler.fit_transform(x)
print("Original Data:",x[:10])
print("Scaled data:",x_encoded[:10])

Original Data:   ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0           ATA        140          289          0    172      0.0
1           NAP        160          180          0    156      1.0
2           ATA        130          283          0     98      0.0
3           ASY        138          214          0    108      1.5
4           NAP        150          195          0    122      0.0
5           NAP        120          339          0    170      0.0
6           ATA        130          237          0    170      0.0
7           ATA        110          208          0    142      0.0
8           ASY        140          207          0    130      1.5
9           ATA        120          284          0    120      0.0
Scaled data:   (0, 1)	1.0
  (0, 29)	1.0
  (0, 159)	1.0
  (0, 204)	1.0
  (0, 287)	1.0
  (0, 307)	1.0
  (1, 2)	1.0
  (1, 34)	1.0
  (1, 66)	1.0
  (1, 204)	1.0
  (1, 276)	1.0
  (1, 316)	1.0
  (2, 1)	1.0
  (2, 22)	1.0
  (2, 154)	1.0
  (2, 204)	1.0
  (2,

In [16]:
#LAbel Encoder
import pandas as pd
df=pd.read_csv("heart_disease.csv")
y=df['HeartDisease']
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_encoded =encoder.fit_transform(y)
print("Original Data:",y[:10])
print("Scaled data:",y_encoded[:10])


Original Data: 0    0
1    1
2    0
3    1
4    0
5    0
6    0
7    0
8    1
9    0
Name: HeartDisease, dtype: int64
Scaled data: [0 1 0 1 0 0 0 0 1 0]


In [18]:
#PCA
label_encoder= LabelEncoder()
df['ChestPainType']=label_encoder.fit_transform(df['ChestPainType'])
x=df.drop(['Name','Age','Gender','HeartDisease','RestingECG','ExerciseAngina','ST_Slope'],axis=1)
y=df['HeartDisease']
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x_pca=pca.fit_transform(x)
print("Original Data:",x[:10])
print("Scaled data:",x_pca[:10])

Original Data:    ChestPainType  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0              1        140          289          0    172      0.0
1              2        160          180          0    156      1.0
2              1        130          283          0     98      0.0
3              0        138          214          0    108      1.5
4              2        150          195          0    122      0.0
5              2        120          339          0    170      0.0
6              1        130          237          0    170      0.0
7              1        110          208          0    142      0.0
8              0        140          207          0    130      1.5
9              1        120          284          0    120      0.0
Scaled data: [[110.12039675 -28.14060464]
 [  0.81999558 -10.64012438]
 [100.54589953  38.07490927]
 [ 32.21426065  28.65500023]
 [ 14.07278669  18.67062655]
 [159.65964016 -30.95910972]
 [ 57.93516906 -31.57396822]
 [ 27.36371114 -12.92

In [7]:
#select k best
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
from sklearn.preprocessing import LabelEncoder 
df=pd.read_csv("heart_disease.csv")
selector=SelectKBest(score_func=chi2,k=3)
label_encoder= LabelEncoder()
df['ChestPainType']=label_encoder.fit_transform(df['ChestPainType'])
x=df.drop(['Name','Age','Gender','HeartDisease','RestingECG','ExerciseAngina','ST_Slope'],axis=1)
y=df['HeartDisease']
x_selected=selector.fit_transform(x,y)
print("Original data:",x[:10])
print("Scaled data:",x_selected[:10])

ValueError: Input X must be non-negative.

In [1]:
#Count vectorizer
from sklearn.feature_extraction.text import CountVectorizer
text=['''Many factors, such as diabetes, high blood pressure, high cholesterol,
and abnormal pulse rate, need to be considered when predicting heart disease. 
Often, the medical data available need to be completed, 
affecting the results in predicting heart disease. 
Machine learning plays a crucial role in the medical field.''']
vectorizer=CountVectorizer()
X_counts=vectorizer.fit_transform(text)
print("Original Data:",text)
print("Scaled Data:",X_counts)

Original Data: ['Many factors, such as diabetes, high blood pressure, high cholesterol,\nand abnormal pulse rate, need to be considered when predicting heart disease. \nOften, the medical data available need to be completed, \naffecting the results in predicting heart disease. \nMachine learning plays a crucial role in the medical field.']
Scaled Data:   (0, 21)	1
  (0, 14)	1
  (0, 32)	1
  (0, 3)	1
  (0, 12)	1
  (0, 17)	2
  (0, 6)	1
  (0, 27)	1
  (0, 7)	1
  (0, 2)	1
  (0, 0)	1
  (0, 28)	1
  (0, 29)	1
  (0, 23)	2
  (0, 34)	2
  (0, 5)	2
  (0, 9)	1
  (0, 35)	1
  (0, 26)	2
  (0, 16)	2
  (0, 13)	2
  (0, 24)	1
  (0, 33)	3
  (0, 22)	2
  (0, 11)	1
  (0, 4)	1
  (0, 8)	1
  (0, 1)	1
  (0, 30)	1
  (0, 18)	2
  (0, 20)	1
  (0, 19)	1
  (0, 25)	1
  (0, 10)	1
  (0, 31)	1
  (0, 15)	1


In [25]:
#TFID vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
text=['''Many factors, such as diabetes, high blood pressure, high cholesterol,
and abnormal pulse rate, need to be considered when predicting heart disease. 
Often, the medical data available need to be completed, 
affecting the results in predicting heart disease. 
Machine learning plays a crucial role in the medical field.''']
vectorizer=TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(text)
print("Original Data:",text)
print("Vector counts:",X_tfidf)


Original Data: ['Many factors, such as diabetes, high blood pressure, high cholesterol,\nand abnormal pulse rate, need to be considered when predicting heart disease. \nOften, the medical data available need to be completed, \naffecting the results in predicting heart disease. \nMachine learning plays a crucial role in the medical field.']
Vector counts:   (0, 15)	0.11867816581938533
  (0, 31)	0.11867816581938533
  (0, 10)	0.11867816581938533
  (0, 25)	0.11867816581938533
  (0, 19)	0.11867816581938533
  (0, 20)	0.11867816581938533
  (0, 18)	0.23735633163877065
  (0, 30)	0.11867816581938533
  (0, 1)	0.11867816581938533
  (0, 8)	0.11867816581938533
  (0, 4)	0.11867816581938533
  (0, 11)	0.11867816581938533
  (0, 22)	0.23735633163877065
  (0, 33)	0.35603449745815596
  (0, 24)	0.11867816581938533
  (0, 13)	0.23735633163877065
  (0, 16)	0.23735633163877065
  (0, 26)	0.23735633163877065
  (0, 35)	0.11867816581938533
  (0, 9)	0.11867816581938533
  (0, 5)	0.23735633163877065
  (0, 34)	0.237356